// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductosAPI.Contexto;

#nullable disable

namespace ProductosAPI.Migrations
{
    [DbContext(typeof(DbContexto))]
    partial class DbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductosAPI.Modelos.Productos", b =>
                {
                    b.Property<int>("id_prod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_prod"));

                    b.Property<string>("descripcion_prod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_prod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("precio_prod")
                        .HasColumnType("real");

                    b.HasKey("id_prod");

                    b.ToTable("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
